CREATE DATABASE app
GO

USE app
GO

CREATE TABLE avatars(
	id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	username VARCHAR(50) NOT NULL,
	image VARBINARY(MAX) NOT NULL
)


CREATE TABLE users(
	id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	email VARCHAR(50) NOT NULL UNIQUE,
	username VARCHAR(50) NOT NULL UNIQUE,
	pwd VARCHAR(50) NOT NULL,
)
GO


CREATE TABLE rooms(
	id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	cr_date DATETIME NOT NULL DEFAULT GETDATE(),
	roomName VARCHAR(50) NOT NUL,
	fromUser VARCHAR(50) NOT NULL,
	toUser VARCHAR(50) NOT NULL
)
GO
	

CREATE TABLE messages(
	id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	content nTEXT NOT NULL,
	cr_date DATETIME NOT NULL DEFAULT GETDATE(),
	idRoom INT FOREIGN KEY REFERENCES rooms(id),
	sender VARCHAR(50) NOT NULL,
	isSeen BIT DEFAULT 0
)
GO


